import pdb
from models.player import Player
from models.team import Team
import repositories.player_repository as player_repository
import repositories.team_repository as team_repository

team1 = Team("Boston Celtics", "TD Garden", 25, 24)
team_repository.save(team1)
team2 = Team("Brooklyn Nets", "Barclays Center", 29, 19)
team_repository.save(team2)
team3 = Team("New York Nicks", "Madison Square Garden", 23, 26)
team_repository.save(team3)
team4 = Team("Philadelphia 76ers", "Wells Fargo Center", 29, 19)
team_repository.save(team4)
team5 = Team("Toronto Raptors", "Scotiabank Arena", 23, 23)
team_repository.save(team5)
team6 = Team("Chicago Bulls", "United Center", 30, 17)
team_repository.save(team6)
team7 = Team("Cleveland Cavaliers", "Rocket Mortgage FieldHouse", 30, 19)
team_repository.save(team7)
team8 = Team("Detroit Pistons", "Little Caesars Arena", 11, 36)
team_repository.save(team8)
team9 = Team("Indiana Pacers", "Gainbridge Fieldhouse", 17, 32)
team_repository.save(team9)
team10 = Team("Milwaukee Bucks", "Fiserv Forum", 30, 20)
team_repository.save(team10)
team11 = Team("Atlanta Hawks", "State Farm Arena", 22, 25)
team_repository.save(team11)
team12 = Team("Charlotte Hornets", "Spectrum Center", 27, 24)
team_repository.save(team12)
team13 = Team("Miami Heat", "FTX Arena", 31, 17)
team_repository.save(team13)
team14 = Team("Orlando Magic", "Amway Center", 9, 40)
team_repository.save(team14)
team15 = Team("Washington Wizards", "Capital One Arena", 23, 25)
team_repository.save(team15)
team16 = Team("Denver Nuggets", "Ball Arena", 26, 21)
team_repository.save(team16)
team17 = Team("Minnestora Timberwolves", "Target Center", 24, 24)
team_repository.save(team17)
team18 = Team("Oklahoma City Thunder", "Paycom Center", 14, 33)
team_repository.save(team18)
team19 = Team("Portland Trail Blazers", "Moda Center", 20, 28)
team_repository.save(team19)
team20 = Team("Utah Jazz", "Vivint Arena", 30, 19)
team_repository.save(team20)
team21 = Team("Golden State Warriors", "Chase Center", 36, 13)
team_repository.save(team21)
team22 = Team("LA Clippers", "Crypto.com Arena", 25, 25)
team_repository.save(team22)
team23 = Team("Los Angeles Lakers", "Crypto.com Arena", 24, 25)
team_repository.save(team23)
team24 = Team("Phoenix Suns", "Footprint Center", 38, 9)
team_repository.save(team24)
team25 = Team("Sacramento Kings", "Golden 1 Center", 18, 32)
team_repository.save(team25)
team26 = Team("Dallas Mavericks", "American Airlines Center", 28, 21)
team_repository.save(team26)
team27 = Team("Houston Rockets", "Toyota Center", 14, 34)
team_repository.save(team27)
team28 = Team("Memphis Grizzlies", "FedExForum", 33, 17)
team_repository.save(team28)
team29 = Team("New Orleans Pelicans", "Smoothie King Center", 18, 29)
team_repository.save(team29)
team30 = Team("San Antonio Spurs", "At&T Center", 18, 32)
team_repository.save(team30)