import pdb
from models.player import Player
from models.team import Team
import repositories.player_repository as player_repository
import repositories.team_repository as team_repository

team1 = Team("Boston Celtics", "TD Garden", 25, 24)
team_repository.save(team1)
team2 = Team("Brooklyn Nets", "Barclays Center", 29, 19)
team_repository.save(team2)
team3 = Team("New York Knicks", "Madison Square Garden", 23, 26)
team_repository.save(team3)
team4 = Team("Philadelphia 76ers", "Wells Fargo Center", 29, 19)
team_repository.save(team4)
team5 = Team("Toronto Raptors", "Scotiabank Arena", 23, 23)
team_repository.save(team5)
team6 = Team("Chicago Bulls", "United Center", 30, 17)
team_repository.save(team6)
team7 = Team("Cleveland Cavaliers", "Rocket Mortgage FieldHouse", 30, 19)
team_repository.save(team7)
team8 = Team("Detroit Pistons", "Little Caesars Arena", 11, 36)
team_repository.save(team8)
team9 = Team("Indiana Pacers", "Gainbridge Fieldhouse", 17, 32)
team_repository.save(team9)
team10 = Team("Milwaukee Bucks", "Fiserv Forum", 30, 20)
team_repository.save(team10)
team11 = Team("Atlanta Hawks", "State Farm Arena", 22, 25)
team_repository.save(team11)
team12 = Team("Charlotte Hornets", "Spectrum Center", 27, 24)
team_repository.save(team12)
team13 = Team("Miami Heat", "FTX Arena", 31, 17)
team_repository.save(team13)
team14 = Team("Orlando Magic", "Amway Center", 9, 40)
team_repository.save(team14)
team15 = Team("Washington Wizards", "Capital One Arena", 23, 25)
team_repository.save(team15)
team16 = Team("Denver Nuggets", "Ball Arena", 26, 21)
team_repository.save(team16)
team17 = Team("Minnesota Timberwolves", "Target Center", 24, 24)
team_repository.save(team17)
team18 = Team("Oklahoma City Thunder", "Paycom Center", 14, 33)
team_repository.save(team18)
team19 = Team("Portland Trail Blazers", "Moda Center", 20, 28)
team_repository.save(team19)
team20 = Team("Utah Jazz", "Vivint Arena", 30, 19)
team_repository.save(team20)
team21 = Team("Golden State Warriors", "Chase Center", 36, 13)
team_repository.save(team21)
team22 = Team("LA Clippers", "Crypto.com Arena", 25, 25)
team_repository.save(team22)
team23 = Team("Los Angeles Lakers", "Crypto.com Arena", 24, 25)
team_repository.save(team23)
team24 = Team("Phoenix Suns", "Footprint Center", 38, 9)
team_repository.save(team24)
team25 = Team("Sacramento Kings", "Golden 1 Center", 18, 32)
team_repository.save(team25)
team26 = Team("Dallas Mavericks", "American Airlines Center", 28, 21)
team_repository.save(team26)
team27 = Team("Houston Rockets", "Toyota Center", 14, 34)
team_repository.save(team27)
team28 = Team("Memphis Grizzlies", "FedExForum", 33, 17)
team_repository.save(team28)
team29 = Team("New Orleans Pelicans", "Smoothie King Center", 18, 29)
team_repository.save(team29)
team30 = Team("San Antonio Spurs", "At&T Center", 18, 32)
team_repository.save(team30)

#Boston Celtics
player1 = Player(team1, "Marcus Smart", "PG")
player_repository.save(player1)
player2 = Player(team1, "Jaylen Brown", "SG")
player_repository.save(player2)
player3 = Player(team1, "Jayson Tatum", "SF")
player_repository.save(player3)
player4 = Player(team1, "Robert Williams III", "PF")
player_repository.save(player4)
player5 = Player(team1, "Al Horford", "C")
player_repository.save(player5)

#Brooklyn Nets
player6 = Player(team2, "Kyrie Irving", "PG")
player_repository.save(player6)
player7 = Player(team2, "James Harden", "SG")
player_repository.save(player7)
player8 = Player(team2, "Kevin Durant", "SF")
player_repository.save(player8)
player9 = Player(team2, "DeAndre' Bembry", "PF")
player_repository.save(player9)
player10 = Player(team2, "Nicolas Claxton", "C")
player_repository.save(player10)

#New York Knicks
player11 = Player(team3, "Kemba Walker", "PG")
player_repository.save(player11)
player12 = Player(team3, "RJ Barrett", "SG")
player_repository.save(player12)
player13 = Player(team3, "Evan Fournier", "SF")
player_repository.save(player13)
player14 = Player(team3, "Julius Randle", "PF")
player_repository.save(player14)
player15 = Player(team3, "Nerles Noel", "C")
player_repository.save(player15)

#Philadelphia 76ers
player16 = Player(team4, "Tyrese Maxey", "PG")
player_repository.save(player16)
player17 = Player(team4, "Seth Curry", "SG")
player_repository.save(player17)
player18 = Player(team4, "Danny Green", "SF")
player_repository.save(player18)
player19 = Player(team4, "Tobias Harris", "PF")
player_repository.save(player19)
player20 = Player(team4, "Joel Embiid", "C")
player_repository.save(player20)

#Raptors
player21 = Player(team5, "Fred VanFleet", "PG")
player_repository.save(player21)
player22 = Player(team5, "Gary Trent Jr.", "SG")
player_repository.save(player22)
player23 = Player(team5, "OG Anunoby", "SF")
player_repository.save(player23)
player24 = Player(team5, "Pascal Siakam", "PF")
player_repository.save(player24)
player25 = Player(team5, "Chris Boucher", "C")
player_repository.save(player25)

#Bulls 
player26 = Player(team6, "Coby White", "PG")
player_repository.save(player26)
player27 = Player(team6, "Zach LaVine", "SG")
player_repository.save(player27)
player28 = Player(team6, "DeMar DeRozan", "SF")
player_repository.save(player28)
player29 = Player(team6, "Alfozo McKinnie", "PF")
player_repository.save(player29)
player30 = Player(team6, "Nikola Vucevic", "C")
player_repository.save(player30)

#Cavaliers
player31 = Player(team7, "Darius Garland", "PG")
player_repository.save(player31)
player32 = Player(team7, "Isaac Okoro", "SG")
player_repository.save(player32)
player33 = Player(team7, "Dean Wade", "SF")
player_repository.save(player33)
player34 = Player(team7, "Evan Mobley", "PF")
player_repository.save(player34)
player35 = Player(team7, "Jarrett Allen", "C")
player_repository.save(player35)

#Pistons
player36 = Player(team8, "Cory Joseph", "PG")
player_repository.save(player36)
player37 = Player(team8, "Cade Cunningham", "SG")
player_repository.save(player37)
player38 = Player(team8, "Hamidou Diallo", "SF")
player_repository.save(player38)
player39 = Player(team8, "Saddiq Bet", "PF")
player_repository.save(player39)
player40 = Player(team8, "Isaiah Stewart", "C")
player_repository.save(player40)

#Pacers
player41 = Player(team9, "Malcolm Brogdon", "PG")
player_repository.save(player41)
player42 = Player(team9, "Caris LeVert", "SG")
player_repository.save(player42)
player43 = Player(team9, "Torrey Craig", "SF")
player_repository.save(player43)
player44 = Player(team9, "Domantas Sabonis", "PF")
player_repository.save(player44)
player45 = Player(team9, "Myles Turner", "C")
player_repository.save(player45)

#Bucks
player46 = Player(team10, "Jrue Holiday", "PG")
player_repository.save(player46)
player47 = Player(team10, "Grayson Allen", "SG")
player_repository.save(player47)
player48 = Player(team10, "Khris Middleton", "SF")
player_repository.save(player48)
player49 = Player(team10, "Giannis Antetokounmpo", "PF")
player_repository.save(player49)
player50 = Player(team10, "Bobby Portis", "C")
player_repository.save(player50)

#Hawks
player51 = Player(team11, "Trae Young", "PG")
player_repository.save(player51)
player52 = Player(team11, "Bogdan Bogdanovic", "SG")
player_repository.save(player52)
player53 = Player(team11, "Kevin Hunter", "SF")
player_repository.save(player53)
player54 = Player(team11, "John Collins", "PF")
player_repository.save(player54)
player55 = Player(team11, "Clint Capela", "C")
player_repository.save(player55)

#Hornets
player56 = Player(team12, "LaMelo Ball", "PG")
player_repository.save(player56)
player57 = Player(team12, "Terry Rozier", "SG")
player_repository.save(player57)
player58 = Player(team12, "Gordon Hayward", "SF")
player_repository.save(player58)
player59 = Player(team12, "Miles Bridges", "PF")
player_repository.save(player59)
player60 = Player(team12, "Mason Plumlee", "C")
player_repository.save(player60)

#Heat
player61 = Player(team13, "Kyle Lowry", "PG")
player_repository.save(player61)
player62 = Player(team13, "Tyler Hero", "SG")
player_repository.save(player62)
player63 = Player(team13, "Jimmy Butler", "SF")
player_repository.save(player63)
player64 = Player(team13, "P.J. Tucker", "PF")
player_repository.save(player64)
player65 = Player(team13, "Bam Adebayo", "C")
player_repository.save(player65)

#Magic
player66 = Player(team14, "Cole Anthony", "PG")
player_repository.save(player66)
player67 = Player(team14, "Gary Harris", "SG")
player_repository.save(player67)
player68 = Player(team14, "Franz Wagner", "SF")
player_repository.save(player68)
player69 = Player(team14, "W. Carter Jr.", "PF")
player_repository.save(player69)
player70 = Player(team14, "Mo Bamba", "C")
player_repository.save(player70)

#Wizards
player71 = Player(team15, "Spencer Dinwiddie", "PG")
player_repository.save(player71)
player72 = Player(team15, "Bradley Beal", "SG")
player_repository.save(player72)
player73 = Player(team15, "K. Caldwell-Pope", "SF")
player_repository.save(player73)
player74 = Player(team15, "Kyle Kuzma", "PF")
player_repository.save(player74)
player75 = Player(team15, "Montrezl Harrell", "C")
player_repository.save(player75)

#Nuggets
player76 = Player(team16, "Monte Morris", "PG")
player_repository.save(player76)
player77 = Player(team16, "Will Barton", "SG")
player_repository.save(player77)
player78 = Player(team16, "Jeff Green", "SF")
player_repository.save(player78)
player79 = Player(team16, "Aaron Gordon", "PF")
player_repository.save(player79)
player80 = Player(team16, "Nikola Jokic", "C")
player_repository.save(player80)

#Timberwolves
player81 = Player(team17, "D'Angelo Russell", "PG")
player_repository.save(player81)
player82 = Player(team17, "Anthony Edwards", "SG")
player_repository.save(player82)
player83 = Player(team17, "Jaden McDaniels", "SF")
player_repository.save(player83)
player84 = Player(team17, "Jarred Vanderbilt", "PF")
player_repository.save(player84)
player85 = Player(team17, "Karl Anthony Towns", "C")
player_repository.save(player85)

#Thunder
player86 = Player(team18, "S. Gilgeous-Alexander", "PG")
player_repository.save(player86)
player87 = Player(team18, "Josh Giddey", "SG")
player_repository.save(player87)
player88 = Player(team18, "Luguetnz Dort", "SF")
player_repository.save(player88)
player89 = Player(team18, "Darius Bazley", "PF")
player_repository.save(player89)
player90 = Player(team18, "J. Robinson-Earl", "C")
player_repository.save(player90)

#Blazers
player91 = Player(team19, "Anfernee Simons", "PG")
player_repository.save(player91)
player92 = Player(team19, "C.J. McCollum", "SG")
player_repository.save(player92)
player93 = Player(team19, "Norman Powell", "SF")
player_repository.save(player93)
player94 = Player(team19, "Robert Covington", "PF")
player_repository.save(player94)
player95 = Player(team19, "Jusuf Nurkic", "C")
player_repository.save(player95)

#Jazz
player96 = Player(team20, "Mike Conley", "PG")
player_repository.save(player96)
player97 = Player(team20, "Donovan Mitchell", "SG")
player_repository.save(player97)
player98 = Player(team20, "Bojan Bogdanovic", "SF")
player_repository.save(player98)
player99 = Player(team20, "Royce O'Neale", "PF")
player_repository.save(player99)
player100 = Player(team20, "Rudy Cobert", "C")
player_repository.save(player100)

#Warriors
player101 = Player(team21, "Stephen Curry", "PG")
player_repository.save(player101)
player102 = Player(team21, "Klay Thompson", "SG")
player_repository.save(player102)
player103 = Player(team21, "Andrew Wiggins", "SF")
player_repository.save(player103)
player104 = Player(team21, "Draymond Green", "PF")
player_repository.save(player104)
player105 = Player(team21, "Kevon Looney", "C")
player_repository.save(player105)

#Clippers
player106 = Player(team22, "Reggie Jackson", "PG")
player_repository.save(player106)
player107 = Player(team22, "Terance Mann", "SG")
player_repository.save(player107)
player108 = Player(team22, "Kawhi Leonard", "SF")
player_repository.save(player108)
player109 = Player(team22, "Nicolas Batum", "PF")
player_repository.save(player109)
player110 = Player(team22, "Ivica Zubac", "C")
player_repository.save(player110)

#Lakers
player111 = Player(team23, "Russell Westbrook", "PG")
player_repository.save(player111)
player112 = Player(team23, "Malik Monk", "SG")
player_repository.save(player112)
player113 = Player(team23, "T. Horton-Tucker", "SF")
player_repository.save(player113)
player114 = Player(team23, "LeBron James", "PF")
player_repository.save(player114)
player115 = Player(team23, "Anthony Davis", "C")
player_repository.save(player115)

#Suns
player116 = Player(team24, "Chris Paul", "PG")
player_repository.save(player116)
player117 = Player(team24, "Devin Booker", "SG")
player_repository.save(player117)
player118 = Player(team24, "Mikal Bridges", "SF")
player_repository.save(player118)
player119 = Player(team24, "Jae Crowder", "PF")
player_repository.save(player119)
player120 = Player(team24, "Deandre Ayton", "C")
player_repository.save(player120)

#Kings
player121 = Player(team25, "De'Aaron Fox", "PG")
player_repository.save(player121)
player122 = Player(team25, "Tyrese Haliburton", "SG")
player_repository.save(player122)
player123 = Player(team25, "Harrison Barnes", "SF")
player_repository.save(player123)
player124 = Player(team25, "Chimezie Metu", "PF")
player_repository.save(player124)
player125 = Player(team25, "Richaun Holmes", "C")
player_repository.save(player125)

#Mavs
player126 = Player(team26, "Luka Doncic", "PG")
player_repository.save(player126)
player127 = Player(team26, "Jalen Brunson", "SG")
player_repository.save(player127)
player128 = Player(team26, "D. Finney-Smith", "SF")
player_repository.save(player128)
player129 = Player(team26, "Maxi Kleber", "PF")
player_repository.save(player129)
player130 = Player(team26, "K. Porzingis", "C")
player_repository.save(player130)

#Rockets
player131 = Player(team27, "Kevin Porter", "PG")
player_repository.save(player131)
player132 = Player(team27, "Jalen Green", "SG")
player_repository.save(player132)
player133 = Player(team27, "Eric Gordon", "SF")
player_repository.save(player133)
player134 = Player(team27, "Jae'Sean Tate", "PF")
player_repository.save(player134)
player135 = Player(team27, "Christian Wood", "C")
player_repository.save(player135)

#Grizzlies
player136 = Player(team28, "Ja Morant", "PG")
player_repository.save(player136)
player137 = Player(team28, "Desmond Bane", "SG")
player_repository.save(player137)
player138 = Player(team28, "Dillon Brooks", "SF")
player_repository.save(player138)
player139 = Player(team28, "Jaren Jackson Jr.", "PF")
player_repository.save(player139)
player140 = Player(team28, "Steven Adams", "C")
player_repository.save(player140)

#Pelicans
player141 = Player(team29, "Devonte' Graham", "PG")
player_repository.save(player141)
player142 = Player(team29, "Brandon Ingram", "SG")
player_repository.save(player142)
player143 = Player(team29, "Josh Hart", "SF")
player_repository.save(player143)
player144 = Player(team29, "Helbert Jones", "PF")
player_repository.save(player144)
player145 = Player(team29, "Jonas Valenciunas", "C")
player_repository.save(player145)

#Spurs
player146 = Player(team30, "Dejounte Murray", "PG")
player_repository.save(player146)
player147 = Player(team30, "Derrick White", "SG")
player_repository.save(player147)
player148 = Player(team30, "Keldon Johnson", "SF")
player_repository.save(player148)
player149 = Player(team30, "Devin Vassell", "PF")
player_repository.save(player149)
player150 = Player(team30, "Jakob Poeltl", "C")
player_repository.save(player150)